env: "debug"
instance: "store1"
use_kafka: true
http_server:
  address: "localhost:8091"
  read_timeout: 5s
  write_timeout: 10s
  idle_timeout: 60s
  shutdown_timeout: 15s
storage:
  database_login: "store1"
  database_password: "python"
  database_address: "localhost"
  database_max_open_connections: 10
  database_name: "store1"
  query_timeout: 5s
secure:
  secure_signature: "it's just secure signature for debug"
  secure_server: "localhost:8095"
kafka:
  kafka_brokers: ["localhost:9092"]
  kafka_topic_update_price: "store.update-price"
prometheus:
  prometheus_port: "9099"
  prometheus_metrics_url: "/metrics"