env: "local"
instance: "store1"
http_server:
  address: "localhost:8091"
  read_timeout: 5s
  write_timeout: 35s
  idle_timeout: 60s
  shutdown_timeout: 15s
  enable_profiler: true
storage:
  database_login: "store1"
  database_password: "python"
  database_address: "localhost"
  database_max_open_connections: 10
  database_name: "store1"
  query_timeout: 5s
  database_viewer_port: 9123
secure:
  secure_signature: "don't need"
  secure_server: "localhost"
  secure_request_timeout: 2s
  secure_username: "store1"
  secure_password: "Python_123"
prometheus:
  prometheus_port: "9099"
  prometheus_metrics_url: "/metrics"