// Code generated by MockGen. DO NOT EDIT.
// Source: service.go

// Package mock_service is a generated GoMock package.
package mock_service

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockMetricsInterface is a mock of MetricsInterface interface.
type MockMetricsInterface struct {
	ctrl     *gomock.Controller
	recorder *MockMetricsInterfaceMockRecorder
}

// MockMetricsInterfaceMockRecorder is the mock recorder for MockMetricsInterface.
type MockMetricsInterfaceMockRecorder struct {
	mock *MockMetricsInterface
}

// NewMockMetricsInterface creates a new mock instance.
func NewMockMetricsInterface(ctrl *gomock.Controller) *MockMetricsInterface {
	mock := &MockMetricsInterface{ctrl: ctrl}
	mock.recorder = &MockMetricsInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMetricsInterface) EXPECT() *MockMetricsInterfaceMockRecorder {
	return m.recorder
}

// CancelOrdersInc mocks base method.
func (m *MockMetricsInterface) CancelOrdersInc() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "CancelOrdersInc")
}

// CancelOrdersInc indicates an expected call of CancelOrdersInc.
func (mr *MockMetricsInterfaceMockRecorder) CancelOrdersInc() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CancelOrdersInc", reflect.TypeOf((*MockMetricsInterface)(nil).CancelOrdersInc))
}

// PlacedInternetOrdersInc mocks base method.
func (m *MockMetricsInterface) PlacedInternetOrdersInc() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "PlacedInternetOrdersInc")
}

// PlacedInternetOrdersInc indicates an expected call of PlacedInternetOrdersInc.
func (mr *MockMetricsInterfaceMockRecorder) PlacedInternetOrdersInc() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PlacedInternetOrdersInc", reflect.TypeOf((*MockMetricsInterface)(nil).PlacedInternetOrdersInc))
}

// PlacedLocalOrdersInc mocks base method.
func (m *MockMetricsInterface) PlacedLocalOrdersInc() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "PlacedLocalOrdersInc")
}

// PlacedLocalOrdersInc indicates an expected call of PlacedLocalOrdersInc.
func (mr *MockMetricsInterfaceMockRecorder) PlacedLocalOrdersInc() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PlacedLocalOrdersInc", reflect.TypeOf((*MockMetricsInterface)(nil).PlacedLocalOrdersInc))
}
